USE BookStore;

INSERT INTO Books (Title, Description, Author, Publisher, PublishedYear, ISBN)
VALUES
    ('The Catcher in the Rye', 'A classic novel about the struggles of a teenage boy', 'J.D. Salinger', 'Little, Brown and Company', 1951, '978-0-316-76948-0'),
    ('To Kill a Mockingbird', 'A novel set in the American South during the 1930s', 'Harper Lee', 'J. B. Lippincott & Co.', 1960, '0-06-112008-1'),
    ('1984', 'A dystopian novel set in a totalitarian society', 'George Orwell', 'Secker & Warburg', 1949, '0-452-28423-6'),
    ('Pride and Prejudice', 'A classic novel about love and class', 'Jane Austen', 'T. Egerton, Whitehall', 1813, 'N/A'),
    ('The Great Gatsby', 'A novel about the American Dream and excess', 'F. Scott Fitzgerald', 'Charles Scribner''s Sons', 1925, '0-7432-7356-7'),
    ('Moby-Dick', 'A tale of the obsessive quest for revenge against a giant white sperm whale', 'Herman Melville', 'Harper & Brothers', 1851, 'N/A'),
    ('War and Peace', 'An epic novel set against the backdrop of the Napoleonic Wars', 'Leo Tolstoy', 'The Russian Messenger', 1869, 'N/A'),
    ('The Hobbit', 'A fantasy novel about a hobbit who embarks on an adventure', 'J.R.R. Tolkien', 'George Allen & Unwin', 1937, '0-395-07122-4'),
    ('Brave New World', 'A dystopian novel depicting a future society', 'Aldous Huxley', 'Chatto & Windus', 1932, '0-09-951847-3'),
    ('The Lord of the Rings', 'A high-fantasy epic', 'J.R.R. Tolkien', 'George Allen & Unwin', 1954, 'N/A'),
    ('The Odyssey', 'An ancient Greek epic poem attributed to Homer', 'Homer', 'N/A', 2000, 'N/A'),
    ('The Shining', 'A horror novel about a family isolated in a haunted hotel', 'Stephen King', 'Doubleday', 1977, '0-385-12167-9'),
    ('Fahrenheit 451', 'A dystopian novel about censorship and suppression of knowledge', 'Ray Bradbury', 'Ballantine Books', 1953, '0-345-34296-8'),
    ('The Chronicles of Narnia', 'A series of seven high fantasy novels', 'C.S. Lewis', 'Geoffrey Bles', 1950-1956, 'Various ISBNs'),
    ('The Road', 'A post-apocalyptic novel about a father and son', 'Cormac McCarthy', 'Alfred A. Knopf', 2006, '0-307-26543-9'),
    ('Harry Potter and the Sorcerer''s Stone', 'The first book in the Harry Potter series', 'J.K. Rowling', 'Bloomsbury', 1997, '0-7475-3269-9'),
    ('The Hitchhiker''s Guide to the Galaxy', 'A comedic science fiction series', 'Douglas Adams', 'Pan Books', 1979, '0-330-25864-8'),
    ('The Sun Also Rises', 'A novel about the "Lost Generation"', 'Ernest Hemingway', 'Scribner''s', 1926, '0-684-80335-0'),
    ('A Tale of Two Cities', 'A historical novel set during the French Revolution', 'Charles Dickens', 'Chapman & Hall', 1859, 'N/A'),
    ('One Hundred Years of Solitude', 'A landmark of the Latin American literary boom', 'Gabriel García Márquez', 'Editorial Sudamericana', 1967, 'N/A'),
    ('The Great Gatsby', 'A classic novel about the American Dream.', 'F. Scott Fitzgerald', 'Scribner', 1925, 'ISBN-9780743273565'),
    ('To Kill a Mockingbird', 'A story of racial injustice in a small Southern town.', 'Harper Lee', 'HarperCollins', 1960, 'ISBN-9780061120084'),
    ('1984', 'A dystopian novel depicting a totalitarian regime.', 'George Orwell', 'Secker & Warburg', 1949, 'ISBN-9780141393049'),
    ('Pride and Prejudice', 'A classic novel about love and class in English society.', 'Jane Austen', 'T. Egerton', 1813, 'ISBN-9780486284736'),
    ('Moby-Dick', 'The epic tale of a sea captains obsession with a white whale.', 'Herman Melville', 'Harper & Brothers', 1851, 'ISBN-9780142196207'),
    ('The Catcher in the Rye', 'A novel about the alienation of a teenager in New York City.', 'J.D. Salinger', 'Little, Brown and Company', 1951, 'ISBN-9780316769488'),
    ('The Hobbit', 'A fantasy novel about a hobbits adventure.', 'J.R.R. Tolkien', 'George Allen & Unwin', 1937, 'ISBN-9780618260307'),
    ('The Lord of the Rings', 'A high-fantasy epic trilogy.', 'J.R.R. Tolkien', 'George Allen & Unwin', 1954, 'ISBN-9780618346271'),
    ('The Alchemist', 'A philosophical novel about a shepherds journey.', 'Paulo Coelho', 'HarperOne', 1988, 'ISBN-9780062315007'),
    ('The Da Vinci Code', 'A mystery thriller involving art and religious symbols.', 'Dan Brown', 'Doubleday', 2003, 'ISBN-9780307277671'),
    ('Gone with the Wind', 'A historical romance set during the American Civil War.', 'Margaret Mitchell', 'Macmillan Publishers', 1936, 'ISBN-9781416548898'),
    ('Brave New World', 'A dystopian novel depicting a futuristic society.', 'Aldous Huxley', 'Chatto & Windus', 1932, 'ISBN-9780099518471'),
    ('The Road', 'A post-apocalyptic novel about a father and sons journey.', 'Cormac McCarthy', 'Knopf', 2006, 'ISBN-9780307265432'),
    ('The Hunger Games', 'A dystopian series about a young womans survival in a deadly game.', 'Suzanne Collins', 'Scholastic', 2008, 'ISBN-9780439023481'),
    ('The Shining', 'A psychological horror novel about a haunted hotel.', 'Stephen King', 'Doubleday', 1977, 'ISBN-9780307743657'),
    ('The Chronicles of Narnia', 'A fantasy series set in the magical land of Narnia.', 'C.S. Lewis', 'Geoffrey Bles', 1950, 'ISBN-9780007117307'),
    ('The Girl with the Dragon Tattoo', 'A mystery thriller involving a journalist and a hacker.', 'Stieg Larsson', 'Norstedts förlag', 2005, 'ISBN-9780307269751'),
    ('Harry Potter and the Sorcerers Stone', 'The first book in the popular Harry Potter series.', 'J.K. Rowling', 'Bloomsbury', 1997, 'ISBN-9780590353427'),
    ('The Road Less Traveled', 'A self-help book about life and love.', 'M. Scott Peck', 'Simon & Schuster', 1978, 'ISBN-9780684847244'),
    ('The Art of War', 'An ancient Chinese treatise on strategy and warfare.', 'Sun Tzu', 'Wuzazu', 1970, 'ISBN-9781590302255')
